erDiagram
    CURSO ||--o{ DISCIPLINA : contem
    DISCIPLINA ||--o{ TURMA : contem
    TURMA ||--|| DOCENTE : possui
    TURMA ||--o{ MATRICULA : possui
    MATRICULA ||--|| DISCENTE : contem
    MATRICULA ||--o| EVASAO : pode_ter

    CURSO {
        int id
        string nome
        string codigo
        int carga_horaria_total
    }
    DISCIPLINA {
        int id
        string nome
        string codigo
        int carga_horaria_total
    }

    TURMA {
        int id
        string periodo
    }

    DOCENTE {
        int id
        string nome
        string login
        string senha
    }

    MATRICULA {
        int id
        float nota_teorica
        float nota_pratica
        int aulas_assistidas
        int tempo_ausente
        int aulas_ausente
        bool tem_evasao
        string status
    }

    DISCENTE {
        int id
        string nome
        string ra
    }

    EVASAO {
        string motivo
    }
